services:
  db:
    image: postgres:15
    container_name: logement_db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
  web:
    build:
      context: ./
      dockerfile: Docker/backend/Dockerfile
    container_name: logement_backend
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
  

