# Generated by Django 5.2.1 on 2025-05-26 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='$images/default.jpg', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('photo', models.ManyToManyField(to='gestion_logement.photo')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Appartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('floor', models.IntegerField(default=0)),
                ('number', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('APP', 'APPARTEMENT'), ('HOU', 'HOUSE')], max_length=3)),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_logement.building')),
                ('photo', models.ManyToManyField(to='gestion_logement.photo')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
